openapi: 3.0.0
info:
  title: superjob-mock-api
  version: 1.0.0
  description: Mock API для получения резюме по ID

paths:
  /2.0/resumes/{id}/:
    get:
      summary: Получить резюме по ID
      parameters:
        - name: id
          in: path
          description: Идентификатор резюме
          required: true
          schema:
            type: integer
            example: 123456
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1111111
        '404':
          description: Резюме не найдено
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Resume not found